routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/admin/kunden/pdf/{id}', 'DynamicPDFController@pdf');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('admin/kunden', 'KundenController');
Route::post('/search', 'KundenController@search')->name('search');;
Route::get('/admin/generate_offer/{id}', 'KundenController@printoffer');
Route::get('/admin/download_pdf/{id}', 'KundenController@download_pdf');
Route::post('/admin/kunden/{id}/save_repayment', 'KundenController@saveRepayment');
Route::get('/admin/kunden/{id}/delete_repayment', 'KundenController@deleteRepayment');
Route::get('/admin/kunden/{id}/delete_timeline', 'KundenController@deleteTimeline');
Route::post('/admin/kunden/{id}/save_timeline', 'KundenController@saveTimeline');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dynamic_pdf', 'DynamicPDFController@index');
Route::get('/dynamic_pdf/pdf', 'DynamicPDFController@pdf');
Route::get('/headmin', 'HomeController@headmin')->name('headmin')->middleware('status');
Route::resource('headmin/group', 'GroupController')->middleware('status');
Route::get('/showgroup/{id}', 'GroupController@show');
Route::resource('headmin/user', 'UserController')->middleware('status');
Route::get('headmin/myprofile', [
    'as' => 'headmin.myprofile',
    'middleware' => 'auth',
    function() {
        return view('headmin.viewprofile');
    }
]);
Route::post('/update_profile', 'ProfileController@update')->name('update_profile');
Route::get('/deletegroup/{id}', 'GroupController@destroy');
Route::post('/creategroup', 'GroupController@store')->name('creategroup');
Route::get('/deleteuser/{id}', 'UserController@destroy');
Route::get('/edituser/{id}', 'UserController@edit');
Route::get('/setgroupleader', 'GroupController@update');

        //
        //
        // //$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
        // $this->post('login', 'Auth\LoginController@login');
        // $this->post('logout', 'Auth\LoginController@logout')->name('logout');
        //
        // // Registration Routes...
        // $this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
        // $this->post('register', 'Auth\RegisterController@register');
        //
        // // Password Reset Routes...
        // $this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        // $this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        // $this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        // $this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

app/Kunden.php
<?php

namespace MVS;

use Illuminate\Database\Eloquent\Model;

class Kunden extends Model
{

  protected $fillable = [
      'vorname', 'nachname', 'user_id',
  ];


  public function myuser(){
    return $this->belongsTo('MVS\User','user_id');
  }
}

app/Http/Controllers/KundenController.php
<?php

namespace MVS\Http\Controllers;

use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use MVS\Angebote;
use MVS\Kunden;
use MVS\timeline;
use Illuminate\Http\Request;
use MVS\Repayment;
use PDF;
use Auth;
use MVS\User;
use MVS\Group;
use DB;

class KundenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index($id=null)
    {
        // if($id==null){
        //   $user=Auth::user();
        //   $kundens = Kunden::where('user_id', $user->id)->with('myuser','myuser.mygroup')->paginate(10);
        //
        //   return view('admin.kunden.index', compact('kundens','user'));
        // } elseif ($id=='0'){
          $kundens = Kunden::with('myuser','myuser.mygroup')->paginate(10);
          $user=Auth::user();
          $user->id='0';
          return view('admin.kunden.index', compact('kundens','user'));
        // } else {
        //   $kundens = Kunden::where('user_id',$id )->with('myuser','myuser.mygroup')->paginate(10);
        //   $user=user::where("id",$id)->get();
        //   $user=$user[0];
        //   return view('admin.kunden.index', compact('kundens','user'));
        // }

    }


    /*

        Funktion das nur eingeloggte Benutzer Kunden anlegen können

    */


    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function create()
    {
        return view('admin.kunden.create');
    }

    public function search(Request $request)
    {

        // $kunden = \DB::table('Kundens');
        $kundens=Kunden::where('id',">",0);
        $user_id=request('user_id');

        if($user_id=='0'){
          $user=Auth::user();
          $user->id='0';
        }else{
          $kunden->where('user_id', $user_id);
          $user=user::where("id",$user_id)->get();
          $user=$user[0];
        }

        $filter_Vorname=request('filter_Vorname');

        if($filter_Vorname!="") $kundens->where('vorname', $filter_Vorname);

        $filter_Nachname=request('filter_Nachname');

        if($filter_Nachname!="") $kundens->where('nachname', $filter_Nachname);

        $filter_KundenID=request('filter_KundenID');

        if($filter_KundenID!="") $kundens->where('id', $filter_KundenID);

        $filter_Stadt=request('filter_Stadt');

        if($filter_Stadt!="") $kundens->where('wohnort', $filter_Stadt);

        $kundens=$kundens->paginate(10);

        return view('admin.kunden.index', compact('kundens','user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,
            [
                'vorname' => 'required',
                'nachname' => 'required',
                'strasse' => 'required',
                'plz' => 'required',
                'wohnort' => 'required',
                'mail' => 'required',
                'telefon' => 'required',
                'geburtsdatum' => 'required'

            ]
        );

        $kunden = new kunden();
        $kunden->user_id = auth()->id();
        $kunden->vorname = request('vorname');
        $kunden->nachname = request('nachname');
        $kunden->strasse = request('strasse');
        $kunden->plz = request('plz');
        $kunden->wohnort = request('wohnort');
        $kunden->mail = request('mail');
        $kunden->telefon = request('telefon');
        $kunden->geburtsdatum = request('geburtsdatum');
        $kunden->save();
        return redirect()->route('kunden.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \MVS\Kunden $kunden
     * @return \Illuminate\Http\Response
     */
    public function show(Kunden $kunden)
    {
        $kunden['offer'] = Angebote::where('customer_id', $kunden->id)->get();
        $repayments = Repayment::where('kundens_id', $kunden->id)->get();

        $timeline = timeline::where('kundens_id', $kunden->id)->get();

//        return $kunden;
        return view('admin.kunden.show', ['kunden' => $kunden, 'repayments' => $repayments, 'timeline' => $timeline]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \MVS\Kunden $kunden
     * @return \Illuminate\Http\Response
     */
    public function edit(Kunden $kunden)
    {
        $users = user::all();

        $Calculations = DB::table('calculation')->where('kunden_id', $kunden->id)->get();
        foreach($Calculations as &$Calculation){
            $Calculation->timeline = DB::table('timeline')->where('kundens_id', $kunden->id)->where('calculation_id', $Calculation->id)->get()->first();
        }

        return view('admin.kunden.edit', compact('kunden','users','Calculations'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \MVS\Kunden $kunden
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Kunden $kunden)
    {
        if ( isset($request->calculation) && $request->calculation == 'calculation' ) {
            $calData = $request->Cal;
            $cid = 0;
            // Calculation data
            // $this->validate($request->Cal,
            //     [
            //         'bank' => 'required',
            //         'annuities' => 'required',
            //         'to_interest' => 'required',
            //         'effectiveness' => 'required',
            //         'fixed_interest_rates' => 'required',
            //         'monthly_loan' => 'required',
            //         'residual_debt_interest_rate' => 'required',
            //         'calculated_luaf_time' => 'required',
            //         'net_loan_amount' => 'required',
            //         'initial_interest' => 'required',
            //         'optional_sound_recovery' => 'required'
            //     ]
            // );
            // dd($request->angebotdate);
            $usedCardId = [];
            foreach ($calData as $value) {
                // 11 fields 
                if(isset($value['id']) && $value['id'] != null && $value['id'] > 0){
                    $calCheck = DB::table('calculation')->where('id', $value['id'])->get()->first();
                    if($calCheck != null){
                        $insertData = [
                            'angebotdate' => $request->angebotdate,
                            'bank' => $value['bank'],
                            'annuities' => $value['annuities'],
                            'to_interest' => $value['to_interest'],
                            'effectiveness' => $value['effectiveness'],
                            'fixed_interest_rates' => $value['fixed_interest_rates'],
                            'monthly_loan' => $value['monthly_loan'],
                            'residual_debt_interest_rate' => $value['residual_debt_interest_rate'],
                            'calculated_luaf_time' => $value['calculated_luaf_time'],
                            'net_loan_amount' => $value['net_loan_amount'],
                            'initial_interest' => $value['initial_interest'],
                            'optional_sound_recovery' => $value['optional_sound_recovery'],
                            'prepared_by' => auth()->user()->id
                        ];
        
                        DB::table('calculation')->where('id', $value['id'])->update($insertData); 
                        $cid = $value['id']; 
                        $usedCardId[] = $cid;
                    }

                } else {
                    $insertData = [
                        'angebotdate' => $request->angebotdate,
                        'bank' => $value['bank'],
                        'kunden_id' => $request->segment(3),
                        'annuities' => $value['annuities'],
                        'to_interest' => $value['to_interest'],
                        'effectiveness' => $value['effectiveness'],
                        'fixed_interest_rates' => $value['fixed_interest_rates'],
                        'monthly_loan' => $value['monthly_loan'],
                        'residual_debt_interest_rate' => $value['residual_debt_interest_rate'],
                        'calculated_luaf_time' => $value['calculated_luaf_time'],
                        'net_loan_amount' => $value['net_loan_amount'],
                        'initial_interest' => $value['initial_interest'],
                        'optional_sound_recovery' => $value['optional_sound_recovery'],
                        'prepared_by' => auth()->user()->id
                    ];
    
                    $cid = DB::table('calculation')->insert($insertData);
                    $cid = DB::getPdo()->lastInsertId();
                    $usedCardId[] = $cid;
                }

                if (isset($value['timeline'])) {
                    if(isset($value['timeline']['id'])){
                        $calCheckTm = timeline::where('id', $value['timeline']['id'])->where('calculation_id', $value['id'])->get()->first();
                        if($calCheckTm != null){
                            $calCheckTm->finanzierungsbedarf_phase_eins = $value['timeline']['finanzierungsbedarf_phase_eins'];
                            $calCheckTm->jahreszins_phase_eins = $value['timeline']['jahreszins_phase_eins'];
                            $calCheckTm->laufzeit_phase_eins = $value['timeline']['laufzeit_phase_eins'];
                            $calCheckTm->rate_monatlich_phase_eins = $value['timeline']['rate_monatlich_phase_eins'];
                            $calCheckTm->finanzierungsbedarf_phase_zwei = $value['timeline']['finanzierungsbedarf_phase_zwei'];

resources/views/admin/kunden/create.blade.php
@extends(Auth::user()->admin == '1' ? 'layouts/headmin' : 'layouts/app')

@section('content')
    <div class="container" style="background-color: #fff; padding-top: 10px;">
        <div class="row">
            <div class="col-md-12 col-md-offset-2">
                <div class="panel panel-default">

                    <div class="panel-heading">Neuen Kunden erstellen</div>

                    <div class="panel-body">
                        @if($errors->any())
                            <div class="alert alert-danger" role="alert">
                                <ul>
                            @foreach($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                                </ul>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>


<form method="post" action="{{route('kunden.store')}}">
                            {{ csrf_field() }}
<div class="container" style="background-color: #fff;">
    <div class="row">

        <div class="col-md-12 col-md-offset-2" >

            <h4>Stammdaten</h4>

                            <div class="form-group">
                                <label for="vorname">Vorname</label>
                                <input type="text" class="form-control" name="vorname" id="vorname" placeholder="Vorname" value="{{ old('vorname') }}" required>
                            </div>
                            <div class="form-group">
                                <label for="nachname">Nachname</label>
                                <input type="text" class="form-control" name="nachname" id="nachname" placeholder="Nachname" value="{{ old('nachname') }}" required>
                            </div>

                            <div class="form-group">
                                <label for="strasse">Straße</label>
                                <input type="text" class="form-control" name="strasse" id="strasse" placeholder="Strasse" value="{{ old('strasse') }}" required>
                            </div>

                            <div class="form-group">
                                <label for="plz">PLZ</label>
                                <input type="number" class="form-control" name="plz" id="plz" placeholder="Plz" value="{{ old('plz') }}" required>
                            </div>

                            <div class="form-group">
                                <label for="wohnort">Wohnort</label>
                                <input type="text" class="form-control" name="wohnort" id="wohnort" placeholder="Wohnort" value="{{ old('wohnort') }}" required>
                            </div>

                             <div class="form-group">
                                <label for="mail">Mail</label>
                                <input type="mail" class="form-control" name="mail" id="mail" placeholder="E-mail" value="{{ old('mail') }}" required>
                            </div>

                            <div class="form-group">
                                <label for="telefon">Telefon</label>
                                <input type="text" class="form-control" name="telefon" id="telefon" placeholder="Telefon" value="{{ old('telefon') }}" required>
                            </div>

                            <div class="form-group">
                                <label for="geburtsdatum">Geburtsdatum</label>
                                <input type="date" class="form-control" name="geburtsdatum" id="geburtsdatum" placeholder="Geburtsdatum" value="{{ old('geburtsdatum') }}" required>
                            </div>

                            <br>

                            <button type="submit" class="btn btn-primary">Kunden anlegen</button>
                            <a href="{{ URL::previous() }}"><button type="submit" class="btn btn-danger">Abbrechen</button></a>

        </div>
    </div></div></form>
@endsection

resources/views/admin/kunden/index.blade.php
@extends(Auth::user()->admin == '1' ? 'layouts/headmin' : 'layouts/app')

<style type="text/css">

.btn-primary {
  background: none !important;
  color: #666 !important;
  border: none !important;
}

#optionen li {
  float: left;
  margin: 0px 10px 0px 10px;
}

#optionen li:first-child {
  margin: 0px 10px 0px 0px
}

</style>
@section('content')
    <div class="container" style="background:#fff; padding-top: 15px;">
        <div class="row">
            <div class="col-md-12 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">

                    <form action="{{route('search')}}" method="POST" >
                    @csrf
                      <h2 style="float: left;">Kunden</h2>
                      <input type="hidden" name="user_id" value="{{$user->id}}">
                      <input type="text" style="float: left; margin-right: 5px; margin-left: 20px;" placeholder="Vorname" name="filter_Vorname">
                      <input type="text" style="float: left; margin-right: 5px;" placeholder="Nachname" name="filter_Nachname">
                      <input type="text" style="float: left; margin-right: 5px;" placeholder="KundenID" name="filter_KundenID">
                      <input type="text" style="float: left; margin-right: 5px;" placeholder="Stadt" name="filter_Stadt">
                      <input type="submit" class="btn btn-sm btn-success" value="Suchen">
                    </form>

                    </div>

                    <div class="panel-body">



                       <div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>KundenID</th>
        <th>Vorname</th>
        <th>Nachname</th>
        <th>Straße</th>
        <th>PLZ</th>
        <th>Stadt</th>
        <th>Telefon</th>
        <th>Geburtsdatum</th>
        <th>User</th>
        <th>Group</th>
        <th style="width: 150px;">Optionen</th>
      </tr>
    </thead>

    @if(count($kundens)>0)

    <tbody>
   @foreach($kundens as $kunden)
      <tr>
        <td><a href="/mvs/mvs/public/admin/kunden/{{ $kunden->id }}/view">{{ $kunden->id }}</a></td>
        <td>{{ $kunden->vorname }}</td>
        <td>{{ $kunden->nachname }}</td>
        <td>{{ $kunden->strasse }}</td>
        <td>{{ $kunden->plz }}</td>
        <td>{{ $kunden->wohnort }}</td>
        <td>{{ $kunden->telefon }}</td>
        <td>{{ $kunden->geburtsdatum }}</td>
        @if(isset($kunden->myuser))
          <td>{{ $kunden->myuser->name }}</td>
          <td>@if(isset($kunden->myuser->mygroup))
              {{ $kunden->myuser->mygroup->name }}
              @else
              @endif
          </td>
          <td>
            <ul id="optionen">
              <li><a href="{{route('kunden.show',$kunden->id)}}"><i class="fas fa-eye fa-lg icon"></i></a></li>
              <li>
                @if(Auth::user()->admin == "1")
                  <a href="{{route('kunden.edit',$kunden->id)}}"><i class="fas fa-pencil-alt fa-lg icon"></i></a>
                @else
                  @if($kunden->myuser->mygroup !== null)
                    @if($kunden->myuser->mygroup->name == Auth::user()->mygroup->name )
                      <a href="{{route('kunden.edit',$kunden->id)}}"><i class="fas fa-pencil-alt fa-lg icon"></i></a>
                    @else
                      <a href="{{route('kunden.edit',$kunden->id)}}" onclick="javascript:return false;" style="color: grey;"><i class="fas fa-pencil-alt fa-lg icon"></i></a>
                    @endif
                  @else
                    <a href="{{route('kunden.edit',$kunden->id)}}" ><i class="fas fa-pencil-alt fa-lg icon"></i></a>
                  @endif
                @endif


              </li>
              <li>
                @if(Auth::user()->admin == "1")
                  <a href="javascript: return false;" data-toggle="modal" data-target="#exampleModal" id='{{route('kunden.destroy',$kunden->id)}}' class="delete"><i class="fas fa-trash-alt fa-lg icon" style="color: red;"></i></a>
                @else

                @endif
              </li>
            </ul>
          </td>
        @else
          <td></td>
          <td></td>
          <td>
            <ul id="optionen">
              <li><a href="{{route('kunden.show',$kunden->id)}}"><i class="fas fa-eye fa-lg icon"></i></a></li>
              <li>

                  <a href="{{route('kunden.edit',$kunden->id)}}"><i class="fas fa-pencil-alt fa-lg icon"></i></a>

              </li>
              <li>
                @if(Auth::user()->admin == "1")
                  <a href="javascript: return false;" data-toggle="modal" data-target="#exampleModal" id='{{route('kunden.destroy',$kunden->id)}}' class="delete"><i class="fas fa-trash-alt fa-lg icon" style="color: red;"></i></a>
                @else

                @endif
              </li>
            </ul>
          </td>
        @endif

      </tr>
      @endforeach
    </tbody>
      @endif
  </table>
  @if($kundens)
    <div class="text-center">
      {!! $kundens->render() !!}
    </div>
  @endif
  </div>
</div>

                            <hr>

                    </div>
                </div>
            </div>
        </div>
    </div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Kunde löschen</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Sind Sie sicher das Sie den Kunden löschen wollen? <br>
        <span style="color: red">Dieser Vorgang kann nicht rückgängig gemacht werden!</span>
      </div>
      <div class="modal-footer">
        <form method="post" action="">
        {{ method_field('DELETE') }}
        {{ csrf_field() }}
       <button  i style="padding: 5px !important;" type="submit" class="btn btn-danger btn-sm"> Löschen</button></li>
    </form>
        <button type="button" class="btn btn-primary" data-dismiss="modal">Abbrechen</button>
      </div>
    </div>
  </div>
</div>


@endsection

resources/views/admin/kunden/show.blade.php
@extends('layouts.app')

@section('content')



    <div class="container" style="background-color: #fff; padding-top: 10px;">

        <div class="row">
            <div class="col-md-8 col-md-offset-8">
                <div class="panel-heading"><h2 class="angebot">Persönliches Angebot für
                        <br> {{ $kunden->vorname }} {{ $kunden->nachname }}</h2></div>
            </div>
            <div class="col-md-4 col-md-offset-4">
                <img style="width: 300px !important;"
                     src="https://www.mkhyp.de/wp-content/uploads/2017/08/logo_positiv.svg">

            </div>

        </div>

        <hr/>
        <div class="row">
            <div class="col-md-12 col-md-offset-12">
                <h4>Übersicht</h4>
                <h5>Persönliche Daten</h5>
                {{ $kunden->vorname }}<br>
                {{ $kunden->nachname }}<br>
                {{ $kunden->strasse }}<br>
                {{ $kunden->plz }}
                {{ $kunden->wohnort }}<br>
                <h5><b>Finanzierungsbedarf</b></h5>
                <table style="width:100%">
                    <tr>
                        <td>Kaufpreis des Objekts</td>
                        <td>{{ number_format(  $kunden->kaufpreis, 2, ',', '.') }}€</td>
                    </tr>
                    <tr>
                        <td>Umbau/Modernisierung</td>
                        <td>{{ number_format( $kunden->kostenumbau, 2, ',', '.') }}€</td>
                    </tr>
                    <tr>
                        <td>Notar/Gericht</td>
                        <td>{{ number_format( $kunden->kostennotar, 2, ',', '.') }}€</td>
                    </tr>

                    <tr>
                        <td>Grunderwerbssteuer</td>
                        <td>{{ number_format( $kunden->grunderwerbssteuer, 2, ',', '.') }}€</td>
                        </tr>

                    <tr>
                        <td>Maklerkosten</td>
                        <td>{{ number_format( $kunden->maklerkosten, 2, ',', '.') }}€</td>
                    </tr>
                    <tr>
                        <td>Gesamtkosten</td>
                        <td>{{ number_format( $kunden->gesamtkosten, 2, ',', '.') }}€</td>
                    </tr>
                    <tr>
                        <td>Eigenkapital</td>
                        <td>{{ number_format( $kunden->eigenkapital, 2, ',', '.') }}€</td>
                    </tr>
                    <tr>
                        <td>Finanzierungsbedarf</td>
                        <td>{{ number_format( $kunden->finanzierungsbedarf, 2, ',', '.') }}€</td>
                    </tr>
                </table>

                <hr>
@foreach ($timeline as $timeline)


<div id="wrapper">

<div class="uper_box">
        <div class="container">
            <div class="box">
                <h2>{{$timeline->finanzierungsbedarf_phase_eins}}€</h2>
            </div>
            <div class="box">
                <div class="top">
                    <ul>
                        <li>{{$timeline->laufzeit_phase_eins}} Jahre</li>
                        <li>{{$timeline->jahreszins_phase_eins}}%</li>
                        <li>dann</li>
                        <li>{{$timeline->laufzeit_phase_zwei}} Jahre</li>
                        <li>{{$timeline->jahreszins_phase_zwei}}%</li>
                    </ul>
                    <div class="clear"></div>
                </div>
                <div class="bottom">
                    <ul>
                        <li>{{$timeline->rate_monatlich_phase_eins}}€</li>
                        <li>- ><br>Restschuld<br>{{$timeline->restschuld_phase_eins}}€</li>
                        <li class="add">{{$timeline->rate_monatlich_phase_zwei}}€</li>
                    </ul>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="box">
                <ul>
                    <li>30jahre</li>
                    <li>Restschuld<br>{{$timeline->restschuld_ende}}€</li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
    </div></div>
<form method="post" action="{{ $timeline->id }}">
          {{ method_field('DELETE') }}
          {{ csrf_field() }}
         <button  i style="padding: 5px !important;" type="submit" class="btn btn-danger btn-sm"> Löschen</button></li>
       </form>


        <a href="{{ $kunden->id }}/edit"> <button  i style="padding: 5px !important;" type="submit" class="btn btn-danger btn-sm">Ändern</button></li></a>


@endforeach


                <hr>

                <br>
                <h5><b>Tilgungsplan </b></h5>
                <div style="max-height: 300px; overflow-y: scroll">
                    <table style="width:100%; max-height: 500px !important;">
                        <thead>
                        <tr>
                            <th>Rückzahlungsdatum</th>
                            <th>Zinsen</th>
                            <th>Tilgung</th>
                            <th>Darlehensrest</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($repayments as $repayment)
                            <tr>
                                <td>{{$repayment->repayment_date}}</td>
                                <td>{{$repayment->zinsen}}</td>
                                <td>{{$repayment->tilgung}}</td>
                                <td>{{$repayment->darlehensrest}}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <br>
                <button class="btn btn-danger" style="color: #fff"><a style="color: #fff"
                                                                      href="{{asset('admin/generate_offer')}}{{ '/'.$kunden->id }}">Angebot
                        erstellen</a></button>

   <hr />
    <h5><b>Angebote </b></h5>


                <ul id="angebote">
                    @foreach($kunden['offer'] as $offer)
                        <li><i class="fa fa-file-pdf" style="font-size:25px;color:red; vertical-align: middle; padding-right: 5px;"></i>Auftragsnummer: <a href="{{asset('admin/download_pdf')}}{{ '/'.$offer->id }}" download="">{{$offer->id}}</a></li>
                    @endforeach
                </ul>
            </div>
        </div>

    </div>
    </div>
    </div>
    </div>
    </div>
@endsection