routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/admin/kunden/pdf/{id}', 'DynamicPDFController@pdf');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('admin/kunden', 'KundenController');
Route::post('/search', 'KundenController@search')->name('search');;
Route::get('/admin/generate_offer/{id}', 'KundenController@printoffer');
Route::get('/admin/download_pdf/{id}', 'KundenController@download_pdf');
Route::post('/admin/kunden/{id}/save_repayment', 'KundenController@saveRepayment');
Route::get('/admin/kunden/{id}/delete_repayment', 'KundenController@deleteRepayment');
Route::get('/admin/kunden/{id}/delete_timeline', 'KundenController@deleteTimeline');
Route::post('/admin/kunden/{id}/save_timeline', 'KundenController@saveTimeline');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dynamic_pdf', 'DynamicPDFController@index');
Route::get('/dynamic_pdf/pdf', 'DynamicPDFController@pdf');
Route::get('/headmin', 'HomeController@headmin')->name('headmin')->middleware('status');
Route::resource('headmin/group', 'GroupController')->middleware('status');
Route::get('/showgroup/{id}', 'GroupController@show');
Route::resource('headmin/user', 'UserController')->middleware('status');
Route::get('headmin/myprofile', [
    'as' => 'headmin.myprofile',
    'middleware' => 'auth',
    function() {
        return view('headmin.viewprofile');
    }
]);
Route::post('/update_profile', 'ProfileController@update')->name('update_profile');
Route::get('/deletegroup/{id}', 'GroupController@destroy');
Route::post('/creategroup', 'GroupController@store')->name('creategroup');
Route::get('/deleteuser/{id}', 'UserController@destroy');
Route::get('/edituser/{id}', 'UserController@edit');
Route::get('/setgroupleader', 'GroupController@update');

        //
        //
        // //$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
        // $this->post('login', 'Auth\LoginController@login');
        // $this->post('logout', 'Auth\LoginController@logout')->name('logout');
        //
        // // Registration Routes...
        // $this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
        // $this->post('register', 'Auth\RegisterController@register');
        //
        // // Password Reset Routes...
        // $this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        // $this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        // $this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        // $this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

app/Group.php
<?php

namespace MVS;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Group extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'address',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */

}

app/Http/Controllers/GroupController.php
<?php

namespace MVS\Http\Controllers;

use Illuminate\Http\Request;
use MVS\User;
use MVS\Group;
use Auth;
use View;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use DB;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $group = new Group;
        $groups= group::all();

        // if(count($groups)==0) {
        //   return view('headmin.group.list');
        // }
        // else {
          $groups = group::paginate(10);
          return view('headmin.group.list',compact('groups'));
        // }
    }

    public function __construct()
    {

        $this->middleware('auth');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('headmin.group.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $group = new Group;
        $data = $this->validate($request, [
            'name' => 'required|string|max:255',

            'postal' => 'required|numeric',
            'city' => 'required|string',
            'street' => 'required|string',
            'streetnum' => 'required|numeric',
        ]);
        $group->name = $data['name'];

        $group->postal_code = $data['postal'];
        $group->city = $data['city'];
        $group->street = $data['street'];
        $group->street_num = $data['streetnum'];

        $group->save();
        return redirect()->route('group.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $groupdata= group::where("id",$id)->get();
      $users=user::where('status',1)->where('group',$id)->get();
      return view('headmin.group.show',compact('groupdata','users'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $groupdata= group::where("id",$id)->get();
        $users=user::where('group',$id)->get();
        return view('headmin.group.edit',compact('groupdata','users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

      $group=group::where('id',$id)->first();

      $data = $this->validate($request, [
          'name' => 'required|string|max:255',

          'postal' => 'required|numeric',
          'city' => 'required|string',
          'street' => 'required|string',
          'streetnum' => 'required|numeric',
      ]);

      $group->name = $data['name'];
      
      $group->postal_code = $data['postal'];
      $group->city = $data['city'];
      $group->street = $data['street'];
      $group->street_num = $data['streetnum'];
      $group->save();


      DB::table('users')
                ->where('group', $id)
                ->update(['status' => 0]);
      DB::table('users')
                ->where('id', $_POST['groupleader'])
                ->update(['status' => 1, 'group' => $id]);
      $groupdata= group::where("id",$id)->get();
      $users=user::all();
      return redirect()->route('group.index');
      // return view('headmin.group.edit',compact('groupdata','users'));



    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $blog = group::findOrFail($id);
        $blog->delete();

        return redirect()->route('group.index');
    }
}

resources/views/headmin/group/create.blade.php
@extends('layouts.headmin')

<style type="text/css">


    .buttons .icon {
        margin-top:35px;
    }
</style>

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Create New Group</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif


                    <h3>This page is for creating a new Group...</h3>
                    @if(!empty($success))
                      <div class="alert alert-success">
                        <strong>Group Created successfully.</strong>
                      </div>
                    @endif
                    <form action="{{ route('creategroup') }}" method="post">
                      {!! csrf_field() !!}

                      <div>
                        <label for="">Name:</label>
                        <input type="text" class="form-control" id="" placeholder="Group Name" name="name" value="" required>
                        @if ($errors->has('name'))
                            <span class="" role="alert">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                      </div>

                      <div>
                        <label for="">Postal Code:</label>
                        <input type="number" class="form-control" id="" placeholder="Postal Code" name="postal" value="" required>
                        @if ($errors->has('postal'))
                            <span class="" role="alert">
                                <strong>{{ $errors->first('postal') }}</strong>
                            </span>
                        @endif
                      </div>

                      <div>
                        <label for="">City:</label>
                        <input type="text" class="form-control" id="" placeholder="City" name="city" value="" required>
                        @if ($errors->has('city'))
                            <span class="" role="alert">
                                <strong>{{ $errors->first('city') }}</strong>
                            </span>
                        @endif
                      </div>

                      <div>
                        <label for="">Street:</label>
                        <input type="text" class="form-control" id="" placeholder="Street" name="street" value="" required>
                        @if ($errors->has('street'))
                            <span class="" role="alert">
                                <strong>{{ $errors->first('street') }}</strong>
                            </span>
                        @endif
                      </div>

                      <div>
                        <label for="">Street Number:</label>
                        <input type="number" class="form-control" id="" placeholder="Street Number" name="streetnum" value="" required>

                      </div>

                      <hr/>
                      <button type="submit" class="btn btn-default">Create</button>
                    </form>


            </div>




        </div>
    </div>
</div>
@endsection

resources/views/headmin/group/edit.blade.php
@extends(Auth::user()->admin == '1' ? 'layouts/headmin' : 'layouts/app')

<style type="text/css">


    .buttons .icon {
        margin-top:35px;
    }
</style>

@section('content')
@if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
@endif
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Edit Group</div>

                <div class="card-body">

                    <form action="{{route('group.update',$groupdata[0]->id )}}" method="post">
                      {!! csrf_field() !!}
                      <input type="hidden" name="_method" value="put" />
                      <div>
                        <label for="">Group Name:</label>
                        <input type="text" class="form-control" id="" placeholder="Group Name" name="name" value="{{ $groupdata[0]->name }}" required>
                        @if ($errors->has('name'))
                            <span class="" role="alert">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                      </div>

                      <div>
                        <label for="">Postal Code:</label>
                        <input type="number" class="form-control" id="" placeholder="Postal Code" name="postal" value="{{ $groupdata[0]->postal_code }}" required>
                        @if ($errors->has('postal'))
                            <span class="" role="alert">
                                <strong>{{ $errors->first('postal') }}</strong>
                            </span>
                        @endif
                      </div>

                      <div>
                        <label for="">City:</label>
                        <input type="text" class="form-control" id="" placeholder="City" name="city" value="{{ $groupdata[0]->city }}" required>
                        @if ($errors->has('city'))
                            <span class="" role="alert">
                                <strong>{{ $errors->first('city') }}</strong>
                            </span>
                        @endif
                      </div>

                      <div>
                        <label for="">Street:</label>
                        <input type="text" class="form-control" id="" placeholder="Street" name="street" value="{{ $groupdata[0]->street }}" required>
                        @if ($errors->has('street'))
                            <span class="" role="alert">
                                <strong>{{ $errors->first('street') }}</strong>
                            </span>
                        @endif
                      </div>

                      <div>
                        <label for="">Street Number:</label>
                        <input type="number" class="form-control" id="" placeholder="Street Number" name="streetnum" value="{{ $groupdata[0]->street_num }}" required>

                      </div>

                      <div>
                        <label for="">Group Leader</label>
                        <select name="groupleader" class="form-control">
                          @foreach($users as $user)
                            @if($user->status == '1')
                              <option value="{{$user->id}}" selected>{{$user->name}}</option>
                            @else
                              <option value="{{$user->id}}">{{$user->name}}</option>
                            @endif
                          @endforeach
                        <select>

                      </div>

                      <hr/>
                      <button type="submit" class="btn btn-default">Update</button>
                    </form>

                </div>




            </div>
        </div>
    </div>
</div>

@endsection

resources/views/headmin/group/list.blade.php
@extends('layouts.headmin')

<style type="text/css">


.btn-primary {
  background: none !important;
  color: #666 !important;
  border: none !important;
}

#optionen li {
  float: left;
  margin: 0px 10px 0px 10px;
}

#optionen li:first-child {
  margin: 0px 10px 0px 0px
}
</style>

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">List Group</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="table-responsive">
                        <table style="width:100%;" class="table">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>City</th>
                                <th>Street</th>
                                <th style="width: 15%;">Options</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($groups as $group)
                                <tr>
                                    <td>{{$group->name}}</td>
                                    <td>{{$group->city}}</td>
                                    <td>{{$group->street}}</td>
                                    <td>
                                        <ul id="optionen">
                                            <li><a href="{{route('group.show',$group->id)}}"><i class="fas fa-eye fa-lg icon"></i></a></li>
                                            <li><a href="{{route('group.edit', $group->id)}}"><i class="fas fa-pencil-alt fa-lg icon"></i></a></li>
                                            <li><a href="javascript: return false;" data-toggle="modal" data-target="#exampleModal" id='{{ route('group.destroy', $group->id) }}' class="delete"><i class="fas fa-trash-alt fa-lg icon" style="color: red;"></i></a></li>
                                        </ul>
                                    </td>
                                </tr>
                            @empty
                                <tr>No Group</tr>
                            @endforelse
                            </tbody>
                        </table>
                        @if($groups)
                          <div class="text-center">
                            {!! $groups->render() !!}
                          </div>
                        @endif
                    </div>


            </div>




        </div>
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Kunde löschen</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Sind Sie sicher das Sie den Kunden löschen wollen? <br>
        <span style="color: red">Dieser Vorgang kann nicht rückgängig gemacht werden!</span>
      </div>
      <div class="modal-footer">
        <form method="post" action="">
        {{ method_field('DELETE') }}
        {{ csrf_field() }}
       <button  i style="padding: 5px !important;" type="submit" class="btn btn-danger btn-sm"> Löschen</button></li>
    </form>
        <button type="button" class="btn btn-primary" data-dismiss="modal">Abbrechen</button>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/headmin/group/show.blade.php
@extends(Auth::user()->admin == '1' ? 'layouts/headmin' : 'layouts/app')

<style type="text/css">


    .buttons .icon {
        margin-top:35px;
    }
</style>

@section('content')
@if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
@endif
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Show Group</div>

                <div class="card-body">

                      {!! csrf_field() !!}
                      <input type="hidden" name="_method" value="put" />
                      <div>
                        <label for="">Group Name:</label>
                        <input type="text" class="form-control" id="" placeholder="Group Name" name="name" value="{{ $groupdata[0]->name }}" readonly>

                      </div>

                      <div>
                        <label for="">Postal Code:</label>
                        <input type="text" class="form-control" id="" placeholder="Address" name="address" value="{{ $groupdata[0]->postal_code }}" readonly>

                      </div>

                      <div>
                        <label for="">City:</label>
                        <input type="text" class="form-control" id="" placeholder="Address" name="address" value="{{ $groupdata[0]->city }}" readonly>

                      </div>

                      <div>
                        <label for="">Street:</label>
                        <input type="text" class="form-control" id="" placeholder="Address" name="address" value="{{ $groupdata[0]->street }}" readonly>

                      </div>

                      <div>
                        <label for="">Street Number:</label>
                        <input type="text" class="form-control" id="" placeholder="Address" name="address" value="{{ $groupdata[0]->street_num }}" readonly>

                      </div>


                      <div>
                        <label for="">Group Leader:</label>

                        @forelse($users as $user)

                            <input type="text" class="form-control" id="" placeholder="Group Leader" name="address" value="{{ $user->name }}" readonly>

                        @empty
                          <input type="text" class="form-control" id="" placeholder="Group Leader" name="address" readonly>
                        @endforelse
                      </div>



                </div>




            </div>
        </div>
    </div>
</div>

@endsection