routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/admin/kunden/pdf/{id}', 'DynamicPDFController@pdf');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('admin/kunden', 'KundenController');
Route::post('/search', 'KundenController@search')->name('search');;
Route::get('/admin/generate_offer/{id}', 'KundenController@printoffer');
Route::get('/admin/download_pdf/{id}', 'KundenController@download_pdf');
Route::post('/admin/kunden/{id}/save_repayment', 'KundenController@saveRepayment');
Route::get('/admin/kunden/{id}/delete_repayment', 'KundenController@deleteRepayment');
Route::get('/admin/kunden/{id}/delete_timeline', 'KundenController@deleteTimeline');
Route::post('/admin/kunden/{id}/save_timeline', 'KundenController@saveTimeline');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dynamic_pdf', 'DynamicPDFController@index');
Route::get('/dynamic_pdf/pdf', 'DynamicPDFController@pdf');
Route::get('/headmin', 'HomeController@headmin')->name('headmin')->middleware('status');
Route::resource('headmin/group', 'GroupController')->middleware('status');
Route::get('/showgroup/{id}', 'GroupController@show');
Route::resource('headmin/user', 'UserController')->middleware('status');
Route::get('headmin/myprofile', [
    'as' => 'headmin.myprofile',
    'middleware' => 'auth',
    function() {
        return view('headmin.viewprofile');
    }
]);
Route::post('/update_profile', 'ProfileController@update')->name('update_profile');
Route::get('/deletegroup/{id}', 'GroupController@destroy');
Route::post('/creategroup', 'GroupController@store')->name('creategroup');
Route::get('/deleteuser/{id}', 'UserController@destroy');
Route::get('/edituser/{id}', 'UserController@edit');
Route::get('/setgroupleader', 'GroupController@update');

        //
        //
        // //$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
        // $this->post('login', 'Auth\LoginController@login');
        // $this->post('logout', 'Auth\LoginController@logout')->name('logout');
        //
        // // Registration Routes...
        // $this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
        // $this->post('register', 'Auth\RegisterController@register');
        //
        // // Password Reset Routes...
        // $this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        // $this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        // $this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        // $this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/new.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    @yield('css')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    <img src="https://www.mkhyp.de/wp-content/uploads/2018/09/mkhyp_Logo_positiv_anfrage_klein.png">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>

                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
<li class="nav-item"><a class="nav-link" href="{{ url('/home') }}">Dashboard</a></li>
<li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>Kunden</a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <!-- <a class="dropdown-item" href="/showcustomer/{{0}}">
                                        View All Customers
                                    </a> -->
                                    <a class="dropdown-item" href="{{route('kunden.index')}}">
                                        Kunden anzeigen
                                    </a>
                                    <a class="dropdown-item" href="{{ url('admin/kunden/create') }}">
                                        Kunden erstellen
                                    </a>
    </div>
</li>
<li class="nav-item"><a class="nav-link" href="{{ url('/support') }}">Support</a></li>
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('headmin.myprofile') }}">
                                        {{ __('Profil') }}
                                    </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>

                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @yield('js')
</body>
</html>

resources/views/layouts/headmin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>mkhyp | Kundenverwaltung</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/jquery.js') }}" defer></script>
    <script src="{{ asset('js/main.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/new.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    @yield('css')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                   <img src="https://www.mkhyp.de/wp-content/uploads/2018/09/mkhyp_Logo_positiv_anfrage_klein.png">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>

                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        <li class="nav-item"><a class="nav-link" href="{{ url('/headmin') }}">Dashboard</a></li>
                        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>Gruppen</a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url('headmin/group') }}">
                                    Gruppen Anzeigen
                                </a>
                                <a class="dropdown-item" href="{{ url('headmin/group/create') }}">
                                    Neue Gruppe hinzufügen
                                </a>
                            </div>
                        </li>
                        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>Benutzer</a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url('headmin/user') }}">
                                    Benutzer Anzeigen
                                </a>
                                <a class="dropdown-item" href="{{ url('headmin/user/create') }}">
                                    Neuen Benutzer hinzufügen
                                </a>
                            </div>
                        </li>
                        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>Kunden</a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <!-- <a class="dropdown-item" href="/showcustomer/{{0}}">
                                    View All Customers
                                </a> -->
                                <a class="dropdown-item" href="{{route('kunden.index')}}">
                                    Kunden anzeigen
                                </a>
                                <a class="dropdown-item" href="{{ url('admin/kunden/create') }}">
                                    Kunden erstellen
                                </a>
                            </div>
                        </li>
<li class="nav-item"><a class="nav-link" href="{{ url('/support') }}">Support</a></li>
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                  <strong>{{ Auth::user()->name }}</strong>   <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('headmin.myprofile') }}">
                                        {{ __('Profil') }}
                                    </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>

                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @yield('js')
</body>
</html>